### ISSUE TITLE
Error building webapp

### ISSUE THREAD

**Issue by gutocosta** [instruct-br/grua#10]
**Describe the bug**
When running webapp docker build, an error occurs in: `Step 16/19: RUN pipenv install --system --deploy`

**To Reproduce**
1. Go to '"/webapp'
2. Run `docker build .`
2. See error

**Expected behavior**
Build image from Dockerfile with sucess.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 2019.12.01

**Comment by oesgalha** [comment]
Closed by #11
